In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
hns = pd.read_csv("Health_Nutrition_and_Statistics.csv")
wdi = pd.read_csv("world_development_indicators.csv")

In [3]:
hns.head()

,Year,Year Code,Country Name,Country Code,Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS],"Community health workers (per 1,000 people) [SH.MED.CMHW.P3]",Current health expenditure per capita (current US$) [SH.XPD.CHEX.PC.CD],"Current health expenditure per capita, PPP (current international $) [SH.XPD.CHEX.PP.CD]",Diabetes prevalence (% of population ages 20 to 79) [SH.STA.DIAB.ZS],"Life expectancy at birth, total (years) [SP.DYN.LE00.IN]",...,People with basic handwashing facilities including soap and water (% of population) [SH.STA.HYGN.ZS],"People with basic handwashing facilities including soap and water, rural (% of rural population) [SH.STA.HYGN.RU.ZS]","People with basic handwashing facilities including soap and water, urban (% of urban population) [SH.STA.HYGN.UR.ZS]",Rural population (% of total population) [SP.RUR.TOTL.ZS],"School enrollment, primary (% gross) [SE.PRM.ENRR]","School enrollment, secondary (% gross) [SE.SEC.ENRR]","School enrollment, tertiary (% gross) [SE.TER.ENRR]","Smoking prevalence, total, ages 15+ [SH.PRV.SMOK]","Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age) [SH.ALC.PCAP.LI]",Urban population (% of total population) [SP.URB.TOTL.IN.ZS]
0,2010,YR2010,Afghanistan,AFG,34.3,..,45.5877498,132.27127854,8.6,61.028,...,37.55213,29.01854,63.58285,76.263,100.0717,50.56725,..,..,0.2,23.737
1,2010,YR2010,Albania,ALB,..,..,203.20858851,478.31473658,4.5,76.562,...,..,..,..,47.837,93.49047,88.10389,44.54925,31.2,7.9,52.163
2,2010,YR2010,Algeria,DZA,..,..,228.39954356,645.28782782,8.5,74.938,...,83.07031,73.06981,87.87966,32.46,115.3376,96.93728,29.88943,15.2,0.7,67.54
3,2010,YR2010,American Samoa,ASM,..,..,..,..,..,..,...,..,..,..,12.406,..,..,..,..,..,87.594
4,2010,YR2010,Andorra,AND,..,..,3754.73134583,3937.48741843,6.6,..,...,..,..,..,11.181,..,..,..,34.8,11.4,88.819

In [4]:
for cname in hns:
    if cname == "Year":
        continue
    elif cname == "Country Name":
        continue
    elif cname == "Country Code":
        continue
    elif cname == "Time Code":
        continue
    else:
        hns[cname] = pd.to_numeric(hns[cname], errors='coerce')

In [5]:
wdi.head()

,Time,Time Code,Country Name,Country Code,"Age dependency ratio, young (% of working-age population) [SP.POP.DPND.YG]","Community health workers (per 1,000 people) [SH.MED.CMHW.P3]",Current health expenditure (% of GDP) [SH.XPD.CHEX.GD.ZS],Current health expenditure per capita (current US$) [SH.XPD.CHEX.PC.CD],Domestic general government health expenditure (% of GDP) [SH.XPD.GHED.GD.ZS],Domestic general government health expenditure (% of general government expenditure) [SH.XPD.GHED.GE.ZS],...,"Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative) [SE.SEC.CUAT.PO.ZS]","Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative) [SE.PRM.CUAT.ZS]","Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative) [SE.TER.CUAT.ST.ZS]","Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative) [SE.SEC.CUAT.UP.ZS]","Educational attainment, at least Master's or equivalent, population 25+, total (%) (cumulative) [SE.TER.CUAT.MS.ZS]","Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative) [SE.TER.CUAT.DO.ZS]",Adjusted net national income per capita (current US$) [NY.ADJ.NNTY.PC.CD],Food imports (% of merchandise imports) [TM.VAL.FOOD.ZS.UN],Food production index (2004-2006 = 100) [AG.PRD.FOOD.XD],Women who believe a husband is justified in beating his wife when she burns the food (%) [SG.VAW.BURN.ZS]
0,2010,YR2010,Argentina,ARG,40.8285418195302,..,8.61366242170334,891.137756347656,5.56834600865841,16.6930332779884,...,18.24677,90.30145,18.24677,..,..,..,8810.35921254626,2.62017860740445,112.66,..
1,2010,YR2010,Australia,AUS,28.1580490459526,..,8.43084380030632,4952.77734375,5.7866245508194,16.2632510066032,...,41.79571,99.86813,37.48809,72.79897,..,..,39980.7729946189,5.48025421094859,96.01,..
2,2010,YR2010,Brazil,BRA,36.314913222797,..,7.94906690716743,891.76416015625,3.57876978814602,9.22007635235786,...,11.2994,..,11.2994,35.92268,..,..,9337.19418795313,4.62144744915168,123.98,..
3,2010,YR2010,China,CHN,25.468924010163,0.81,4.20799143612385,187.733474731445,2.18420960009098,8.75092446804047,...,..,..,8.81204,22.316,0.37868,..,3459.18181520509,4.61500308737094,119.96,..
4,2010,YR2010,France,FRA,28.5724568566086,..,11.2390235066414,4593.392578125,8.58061164617538,15.0849774479866,...,24.51876,98.43424,24.43201,61.89694,..,..,34311.5177305945,8.48877850557032,100.61,..

In [6]:
hns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1958 entries, 0 to 1957
Data columns (total 39 columns):
 #   Column                                                                                                                 Non-Null Count  Dtype
---  ------                                                                                                                 --------------  -----
 0   Year                                                                                                                   1955 non-null   object
 1   Year Code                                                                                                              0 non-null      float64
 2   Country Name                                                                                                           1953 non-null   object
 3   Country Code                                                                                                           1953 non-null   object
 4   Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS]                                                  654 non-null    float64
 5   Community health workers (per 1,000 people) [SH.MED.CMHW.P3]                                                           45 non-null     float64
 6   Current health expenditure per capita (current US$) [SH.XPD.CHEX.PC.CD]                                                1306 non-null   float64
 7   Current health expenditure per capita, PPP (current international $) [SH.XPD.CHEX.PP.CD]                               1305 non-null   float64
 8   Diabetes prevalence (% of population ages 20 to 79) [SH.STA.DIAB.ZS]                                                   205 non-null    float64
 9   Life expectancy at birth, total (years) [SP.DYN.LE00.IN]                                                               1600 non-null   float64
 10  Labor force, total [SL.TLF.TOTL.IN]                                                                                    1676 non-null   float64
 11  Literacy rate, adult total (% of people ages 15 and above) [SE.ADT.LITR.ZS]                                            416 non-null    float64
 12  Literacy rate, youth total (% of people ages 15-24) [SE.ADT.1524.LT.ZS]                                                409 non-null    float64
 13  Net migration [SM.POP.NETM]                                                                                            388 non-null    float64
 14  People using at least basic drinking water services (% of population) [SH.H2O.BASW.ZS]                                 1708 non-null   float64
 15  People using at least basic drinking water services, rural (% of rural population) [SH.H2O.BASW.RU.ZS]                 1340 non-null   float64
 16  People using at least basic drinking water services, urban (% of urban population) [SH.H2O.BASW.UR.ZS]                 1404 non-null   float64
 17  People practicing open defecation, urban (% of urban population) [SH.STA.ODFC.UR.ZS]                                   1388 non-null   float64
 18  People practicing open defecation, rural (% of rural population) [SH.STA.ODFC.RU.ZS]                                   1311 non-null   float64
 19  People practicing open defecation (% of population) [SH.STA.ODFC.ZS]                                                   1662 non-null   float64
 20  People using at least basic sanitation services (% of population) [SH.STA.BASS.ZS]                                     1686 non-null   float64
 21  People using at least basic sanitation services, rural (% of rural population) [SH.STA.BASS.RU.ZS]                     1332 non-null   float64
 22  People using at least basic sanitation services, urban  (% of urban population) [SH.STA.BASS.UR.ZS]                    1388 non-null   float64
 23  People using safely managed drinking water services (% of population) [SH.H2O.SMDW.ZS]                                 872 non-null    float64
 24  People using safely managed drinking water services, rural (% of rural population) [SH.H2O.SMDW.RU.ZS]                 272 non-null    float64
 25  People using safely managed drinking water services, urban (% of urban population) [SH.H2O.SMDW.UR.ZS]                 440 non-null    float64
 26  People using safely managed sanitation services (% of population) [SH.STA.SMSS.ZS]                                     752 non-null    float64
 27  People using safely managed sanitation services, rural (% of rural population) [SH.STA.SMSS.RU.ZS]                     352 non-null    float64
 28  People using safely managed sanitation services, urban  (% of urban population) [SH.STA.SMSS.UR.ZS]                    600 non-null    float64
 29  People with basic handwashing facilities including soap and water (% of population) [SH.STA.HYGN.ZS]                   634 non-null    float64
 30  People with basic handwashing facilities including soap and water, rural (% of rural population) [SH.STA.HYGN.RU.ZS]   631 non-null    float64
 31  People with basic handwashing facilities including soap and water, urban (% of urban population) [SH.STA.HYGN.UR.ZS]   627 non-null    float64
 32  Rural population (% of total population) [SP.RUR.TOTL.ZS]                                                              1928 non-null   float64
 33  School enrollment, primary (% gross) [SE.PRM.ENRR]                                                                     1332 non-null   float64
 34  School enrollment, secondary (% gross) [SE.SEC.ENRR]                                                                   1155 non-null   float64
 35  School enrollment, tertiary (% gross) [SE.TER.ENRR]                                                                    1055 non-null   float64
 36  Smoking prevalence, total, ages 15+ [SH.PRV.SMOK]                                                                      1022 non-null   float64
 37  Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age) [SH.ALC.PCAP.LI]  374 non-null    float64
 38  Urban population (% of total population) [SP.URB.TOTL.IN.ZS]                                                           1928 non-null   float64
dtypes: float64(36), object(3)
memory usage: 596.7+ KB

In [7]:
for cname in wdi:
    if cname == "Year":
        continue
    elif cname == "Country Name":
        continue
    elif cname == "Country Code":
        continue
    elif cname == "Time Code":
        continue
    else:
        wdi[cname] = pd.to_numeric(wdi[cname], errors='coerce')

In [8]:
wdi.head()

,Time,Time Code,Country Name,Country Code,"Age dependency ratio, young (% of working-age population) [SP.POP.DPND.YG]","Community health workers (per 1,000 people) [SH.MED.CMHW.P3]",Current health expenditure (% of GDP) [SH.XPD.CHEX.GD.ZS],Current health expenditure per capita (current US$) [SH.XPD.CHEX.PC.CD],Domestic general government health expenditure (% of GDP) [SH.XPD.GHED.GD.ZS],Domestic general government health expenditure (% of general government expenditure) [SH.XPD.GHED.GE.ZS],...,"Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative) [SE.SEC.CUAT.PO.ZS]","Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative) [SE.PRM.CUAT.ZS]","Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative) [SE.TER.CUAT.ST.ZS]","Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative) [SE.SEC.CUAT.UP.ZS]","Educational attainment, at least Master's or equivalent, population 25+, total (%) (cumulative) [SE.TER.CUAT.MS.ZS]","Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative) [SE.TER.CUAT.DO.ZS]",Adjusted net national income per capita (current US$) [NY.ADJ.NNTY.PC.CD],Food imports (% of merchandise imports) [TM.VAL.FOOD.ZS.UN],Food production index (2004-2006 = 100) [AG.PRD.FOOD.XD],Women who believe a husband is justified in beating his wife when she burns the food (%) [SG.VAW.BURN.ZS]
0,2010.0,YR2010,Argentina,ARG,40.828542,NaN,8.613662,891.137756,5.568346,16.693033,...,18.24677,90.30145,18.24677,NaN,NaN,NaN,8810.359213,2.620179,112.66,NaN
1,2010.0,YR2010,Australia,AUS,28.158049,NaN,8.430844,4952.777344,5.786625,16.263251,...,41.79571,99.86813,37.48809,72.79897,NaN,NaN,39980.772995,5.480254,96.01,NaN
2,2010.0,YR2010,Brazil,BRA,36.314913,NaN,7.949067,891.764160,3.578770,9.220076,...,11.29940,NaN,11.29940,35.92268,NaN,NaN,9337.194188,4.621447,123.98,NaN
3,2010.0,YR2010,China,CHN,25.468924,0.81,4.207991,187.733475,2.184210,8.750924,...,NaN,NaN,8.81204,22.31600,0.37868,NaN,3459.181815,4.615003,119.96,NaN
4,2010.0,YR2010,France,FRA,28.572457,NaN,11.239024,4593.392578,8.580612,15.084977,...,24.51876,98.43424,24.43201,61.89694,NaN,NaN,34311.517731,8.488779,100.61,NaN

In [9]:
wdi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1958 entries, 0 to 1957
Data columns (total 42 columns):
 #   Column                                                                                                                       Non-Null Count  Dtype
---  ------                                                                                                                       --------------  -----
 0   Time                                                                                                                         1953 non-null   float64
 1   Time Code                                                                                                                    1953 non-null   object
 2   Country Name                                                                                                                 1953 non-null   object
 3   Country Code                                                                                                                 1953 non-null   object
 4   Age dependency ratio, young (% of working-age population) [SP.POP.DPND.YG]                                                   1739 non-null   float64
 5   Community health workers (per 1,000 people) [SH.MED.CMHW.P3]                                                                 45 non-null     float64
 6   Current health expenditure (% of GDP) [SH.XPD.CHEX.GD.ZS]                                                                    1484 non-null   float64
 7   Current health expenditure per capita (current US$) [SH.XPD.CHEX.PC.CD]                                                      1484 non-null   float64
 8   Domestic general government health expenditure (% of GDP) [SH.XPD.GHED.GD.ZS]                                                1492 non-null   float64
 9   Domestic general government health expenditure (% of general government expenditure) [SH.XPD.GHED.GE.ZS]                     1492 non-null   float64
 10  Domestic general government health expenditure (% of current health expenditure) [SH.XPD.GHED.CH.ZS]                         1484 non-null   float64
 11  Current health expenditure per capita, PPP (current international $) [SH.XPD.CHEX.PP.CD]                                     1481 non-null   float64
 12  Domestic general government health expenditure per capita (current US$) [SH.XPD.GHED.PC.CD]                                  1492 non-null   float64
 13  Domestic general government health expenditure per capita, PPP (current international $) [SH.XPD.GHED.PP.CD]                 1489 non-null   float64
 14  Domestic private health expenditure (% of current health expenditure) [SH.XPD.PVTD.CH.ZS]                                    1484 non-null   float64
 15  Domestic private health expenditure per capita (current US$) [SH.XPD.PVTD.PC.CD]                                             1484 non-null   float64
 16  Domestic private health expenditure per capita, PPP (current international $) [SH.XPD.PVTD.PP.CD]                            1481 non-null   float64
 17  External health expenditure per capita, PPP (current international $) [SH.XPD.EHEX.PP.CD]                                    1489 non-null   float64
 18  External health expenditure per capita (current US$) [SH.XPD.EHEX.PC.CD]                                                     1492 non-null   float64
 19  ARI treatment (% of children under 5 taken to a health provider) [SH.STA.ARIC.ZS]                                            171 non-null    float64
 20  Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS]                                                        654 non-null    float64
 21  Population density (people per sq. km of land area) [EN.POP.DNST]                                                            1923 non-null   float64
 22  Land area (sq. km) [AG.LND.TOTL.K2]                                                                                          1930 non-null   float64
 23  Urban land area (sq. km) [AG.LND.TOTL.UR.K2]                                                                                 179 non-null    float64
 24  Population in the largest city (% of urban population) [EN.URB.LCTY.UR.ZS]                                                   1370 non-null   float64
 25  Population in largest city [EN.URB.LCTY]                                                                                     1370 non-null   float64
 26  Age dependency ratio, old (% of working-age population) [SP.POP.DPND.OL]                                                     1739 non-null   float64
 27  Age dependency ratio (% of working-age population) [SP.POP.DPND]                                                             1739 non-null   float64
 28  Coverage of social insurance programs (% of population) [per_si_allsi.cov_pop_tot]                                           169 non-null    float64
 29  Coverage of social insurance programs in poorest quintile (% of population) [per_si_allsi.cov_q1_tot]                        169 non-null    float64
 30  Coverage of social insurance programs in richest quintile (% of population) [per_si_allsi.cov_q5_tot]                        169 non-null    float64
 31  Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative) [SE.SEC.CUAT.LO.ZS]       517 non-null    float64
 32  Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative) [SE.SEC.CUAT.PO.ZS]        516 non-null    float64
 33  Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative) [SE.PRM.CUAT.ZS]            466 non-null    float64
 34  Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative) [SE.TER.CUAT.ST.ZS]  521 non-null    float64
 35  Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative) [SE.SEC.CUAT.UP.ZS]       543 non-null    float64
 36  Educational attainment, at least Master's or equivalent, population 25+, total (%) (cumulative) [SE.TER.CUAT.MS.ZS]          291 non-null    float64
 37  Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative) [SE.TER.CUAT.DO.ZS]                   251 non-null    float64
 38  Adjusted net national income per capita (current US$) [NY.ADJ.NNTY.PC.CD]                                                    1391 non-null   float64
 39  Food imports (% of merchandise imports) [TM.VAL.FOOD.ZS.UN]                                                                  1405 non-null   float64
 40  Food production index (2004-2006 = 100) [AG.PRD.FOOD.XD]                                                                     1409 non-null   float64
 41  Women who believe a husband is justified in beating his wife when she burns the food (%) [SG.VAW.BURN.ZS]                    88 non-null     float64
dtypes: float64(39), object(3)
memory usage: 642.6+ KB

In [10]:
i=0
enough_info_wdi = list()
not_enough_info_wdi = list()
threshold_wdi = 150

for p in wdi:
    i=0
    for j in range(len(wdi.groupby(by="Country Name").count())):
        if p == "Country Name":
            continue
        
        elif wdi.groupby(by="Country Name").any()[p][j] == True:
            i+=1
    if i < threshold_wdi:
        not_enough_info_wdi.append(p)
    else:
        enough_info_wdi.append(p)

In [11]:
print("How many features in World Development Indicators not have enough data: {} ".format(len(not_enough_info_wdi)))

How many features in World Development Indicators not have enough data: 14

In [12]:
print("How many features in World Development Indicators have enough data: {} ".format(len(enough_info_wdi)))

How many features in World Development Indicators have enough data: 28

In [13]:
i=0
enough_info_hns = list()
not_enough_info_hns = list()
threshold_hns = 150

for p in hns:
    i=0
    for j in range(len(hns.groupby(by="Country Name").count())):
        if p == "Country Name":
            continue
        
        elif hns.groupby(by="Country Name").any()[p][j] == True:
            i+=1
    if i < threshold_hns:
        not_enough_info_hns.append(p)
    else:
        enough_info_hns.append(p)

In [14]:
print("How many features in Health Nutrition and Population not have enough data: {} ".format(len(not_enough_info_hns)))

How many features in Health Nutrition and Population not have enough data: 16

In [15]:
print("How many features in Health Nutrition and Population have enough data: {} ".format(len(enough_info_hns)))

How many features in Health Nutrition and Population have enough data: 23

In [16]:


for name in not_enough_info_wdi:
    if name == "Country Name":
        pass
    else:
        del wdi[name]

In [17]:
for name in not_enough_info_hns:
    if name == "Country Name":
        pass
    elif name == "Year Code":
        pass   
    else:
        del hns[name]

In [18]:
hns.head()

,Year,Year Code,Country Name,Country Code,Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS],Current health expenditure per capita (current US$) [SH.XPD.CHEX.PC.CD],"Current health expenditure per capita, PPP (current international $) [SH.XPD.CHEX.PP.CD]",Diabetes prevalence (% of population ages 20 to 79) [SH.STA.DIAB.ZS],"Life expectancy at birth, total (years) [SP.DYN.LE00.IN]","Labor force, total [SL.TLF.TOTL.IN]",...,"People using at least basic drinking water services, urban (% of urban population) [SH.H2O.BASW.UR.ZS]",People using at least basic sanitation services (% of population) [SH.STA.BASS.ZS],"People using at least basic sanitation services, rural (% of rural population) [SH.STA.BASS.RU.ZS]","People using at least basic sanitation services, urban (% of urban population) [SH.STA.BASS.UR.ZS]",Rural population (% of total population) [SP.RUR.TOTL.ZS],"School enrollment, primary (% gross) [SE.PRM.ENRR]","School enrollment, secondary (% gross) [SE.SEC.ENRR]","School enrollment, tertiary (% gross) [SE.TER.ENRR]","Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age) [SH.ALC.PCAP.LI]",Urban population (% of total population) [SP.URB.TOTL.IN.ZS]
0,2010,NaN,Afghanistan,AFG,34.3,45.587750,132.271279,8.6,61.028,9572580.0,...,73.517656,34.177028,30.342450,46.496882,76.263,100.07170,50.56725,NaN,0.2,23.737
1,2010,NaN,Albania,ALB,NaN,203.208589,478.314737,4.5,76.562,1225928.0,...,92.873123,95.571700,92.949267,97.976648,47.837,93.49047,88.10389,44.54925,7.9,52.163
2,2010,NaN,Algeria,DZA,NaN,228.399544,645.287828,8.5,74.938,11082664.0,...,95.027100,86.560430,78.913464,90.235596,32.460,115.33760,96.93728,29.88943,0.7,67.540
3,2010,NaN,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,62.528187,NaN,NaN,12.406,NaN,NaN,NaN,NaN,87.594
4,2010,NaN,Andorra,AND,NaN,3754.731346,3937.487418,6.6,NaN,NaN,...,100.000000,99.999997,100.000000,100.000000,11.181,NaN,NaN,NaN,11.4,88.819

In [19]:
wdi.head()

,Time,Time Code,Country Name,Country Code,"Age dependency ratio, young (% of working-age population) [SP.POP.DPND.YG]",Current health expenditure (% of GDP) [SH.XPD.CHEX.GD.ZS],Current health expenditure per capita (current US$) [SH.XPD.CHEX.PC.CD],Domestic general government health expenditure (% of GDP) [SH.XPD.GHED.GD.ZS],Domestic general government health expenditure (% of general government expenditure) [SH.XPD.GHED.GE.ZS],Domestic general government health expenditure (% of current health expenditure) [SH.XPD.GHED.CH.ZS],...,Population density (people per sq. km of land area) [EN.POP.DNST],Land area (sq. km) [AG.LND.TOTL.K2],Urban land area (sq. km) [AG.LND.TOTL.UR.K2],Population in the largest city (% of urban population) [EN.URB.LCTY.UR.ZS],Population in largest city [EN.URB.LCTY],"Age dependency ratio, old (% of working-age population) [SP.POP.DPND.OL]",Age dependency ratio (% of working-age population) [SP.POP.DPND],Adjusted net national income per capita (current US$) [NY.ADJ.NNTY.PC.CD],Food imports (% of merchandise imports) [TM.VAL.FOOD.ZS.UN],Food production index (2004-2006 = 100) [AG.PRD.FOOD.XD]
0,2010.0,YR2010,Argentina,ARG,40.828542,8.613662,891.137756,5.568346,16.693033,64.645511,...,14.904302,2.736690e+06,55032.20313,38.444270,14245871.0,15.987427,56.815969,8810.359213,2.620179,112.66
1,2010.0,YR2010,Australia,AUS,28.158049,8.430844,4952.777344,5.786625,16.263251,68.636537,...,2.867859,7.682300e+06,36745.70313,22.197049,4165739.0,19.790405,47.948454,39980.772995,5.480254,96.01
2,2010.0,YR2010,Brazil,BRA,36.314913,7.949067,891.764160,3.578770,9.220076,45.021254,...,23.415932,8.358140e+06,134981.37500,11.911058,19659808.0,9.978387,46.293300,9337.194188,4.621447,123.98
3,2010.0,YR2010,China,CHN,25.468924,4.207991,187.733475,2.184210,8.750924,51.906228,...,142.487740,9.388211e+06,380679.30000,3.084943,20314309.0,11.020799,36.489723,3459.181815,4.615003,119.96
4,2010.0,YR2010,France,FRA,28.572457,11.239024,4593.392578,8.580612,15.084977,76.346594,...,118.759340,5.475570e+05,86463.06250,20.525568,10460118.0,26.058449,54.630906,34311.517731,8.488779,100.61

In [20]:
samefeatures = list()
for wdix in wdi:
    for hnsx in hns:
        if wdix == hnsx:
            samefeatures.append(wdix)
            
samefeatures

['Country Name',
 'Country Code',
 'Current health expenditure per capita (current US$) [SH.XPD.CHEX.PC.CD]',
 'Current health expenditure per capita, PPP (current international $) [SH.XPD.CHEX.PP.CD]',
 'Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS]']

In [21]:
del samefeatures[1]
del samefeatures[0]

samefeatures

['Current health expenditure per capita (current US$) [SH.XPD.CHEX.PC.CD]',
 'Current health expenditure per capita, PPP (current international $) [SH.XPD.CHEX.PP.CD]',
 'Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS]']

In [22]:
for wdiname in wdi:
    for same in samefeatures:
        if wdiname==same:
            del wdi[wdiname]

Now there is no common feature between hns and wdi

In [23]:
pd.to_numeric(hns["Year"],errors="coerce")

0       2010.0
1       2010.0
2       2010.0
3       2010.0
4       2010.0
         ...
1953       NaN
1954       NaN
1955       NaN
1956       NaN
1957       NaN
Name: Year, Length: 1958, dtype: float64

In [24]:
for i in range(len(hns)):
    if (hns[hns.index == i]["Year"] == "NaN").bool():
        del hns[hns.index == i]

In [25]:
hns = hns[hns["Country Code"].isnull() == False]

In [26]:
wdi = wdi[wdi["Country Code"].isnull() == False]

In [27]:
del hns["Year Code"]

In [28]:
hns

,Year,Country Name,Country Code,Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS],Current health expenditure per capita (current US$) [SH.XPD.CHEX.PC.CD],"Current health expenditure per capita, PPP (current international $) [SH.XPD.CHEX.PP.CD]",Diabetes prevalence (% of population ages 20 to 79) [SH.STA.DIAB.ZS],"Life expectancy at birth, total (years) [SP.DYN.LE00.IN]","Labor force, total [SL.TLF.TOTL.IN]","Literacy rate, adult total (% of people ages 15 and above) [SE.ADT.LITR.ZS]",...,"People using at least basic drinking water services, urban (% of urban population) [SH.H2O.BASW.UR.ZS]",People using at least basic sanitation services (% of population) [SH.STA.BASS.ZS],"People using at least basic sanitation services, rural (% of rural population) [SH.STA.BASS.RU.ZS]","People using at least basic sanitation services, urban (% of urban population) [SH.STA.BASS.UR.ZS]",Rural population (% of total population) [SP.RUR.TOTL.ZS],"School enrollment, primary (% gross) [SE.PRM.ENRR]","School enrollment, secondary (% gross) [SE.SEC.ENRR]","School enrollment, tertiary (% gross) [SE.TER.ENRR]","Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age) [SH.ALC.PCAP.LI]",Urban population (% of total population) [SP.URB.TOTL.IN.ZS]
0,2010,Afghanistan,AFG,34.3,45.587750,132.271279,8.6,61.028,9572580.0,NaN,...,73.517656,34.177028,30.342450,46.496882,76.263,100.07170,50.56725,NaN,0.2,23.737
1,2010,Albania,ALB,NaN,203.208589,478.314737,4.5,76.562,1225928.0,NaN,...,92.873123,95.571700,92.949267,97.976648,47.837,93.49047,88.10389,44.54925,7.9,52.163
2,2010,Algeria,DZA,NaN,228.399544,645.287828,8.5,74.938,11082664.0,NaN,...,95.027100,86.560430,78.913464,90.235596,32.460,115.33760,96.93728,29.88943,0.7,67.540
3,2010,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,62.528187,NaN,NaN,12.406,NaN,NaN,NaN,NaN,87.594
4,2010,Andorra,AND,NaN,3754.731346,3937.487418,6.6,NaN,NaN,NaN,...,100.000000,99.999997,100.000000,100.000000,11.181,NaN,NaN,NaN,11.4,88.819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1948,2018,Virgin Islands (U.S.),VIR,NaN,NaN,NaN,NaN,NaN,51011.0,NaN,...,NaN,NaN,NaN,NaN,4.279,NaN,NaN,NaN,NaN,95.721
1949,2018,West Bank and Gaza,PSE,NaN,NaN,NaN,NaN,NaN,1267515.0,97.21861,...,NaN,NaN,NaN,NaN,23.836,98.60411,89.48775,44.25381,NaN,76.164
1950,2018,"Yemen, Rep.",YEM,NaN,NaN,NaN,NaN,NaN,6625451.0,NaN,...,NaN,NaN,NaN,NaN,63.358,NaN,NaN,NaN,NaN,36.642
1951,2018,Zambia,ZMB,NaN,NaN,NaN,NaN,NaN,7183708.0,86.74796,...,NaN,NaN,NaN,NaN,56.479,NaN,NaN,NaN,NaN,43.521
1952,2018,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,6948204.0,NaN,...,NaN,NaN,NaN,NaN,67.791,NaN,NaN,NaN,NaN,32.209

In [30]:
hns = hns.sort_values(by=["Country Name","Year"])
hns.reset_index(drop=True,inplace=True)

In [31]:
wdi = wdi.sort_values(by=["Country Name","Time"])
wdi.reset_index(drop=True,inplace=True)

In [32]:
wdi

,Time,Time Code,Country Name,Country Code,"Age dependency ratio, young (% of working-age population) [SP.POP.DPND.YG]",Current health expenditure (% of GDP) [SH.XPD.CHEX.GD.ZS],Domestic general government health expenditure (% of GDP) [SH.XPD.GHED.GD.ZS],Domestic general government health expenditure (% of general government expenditure) [SH.XPD.GHED.GE.ZS],Domestic general government health expenditure (% of current health expenditure) [SH.XPD.GHED.CH.ZS],Domestic general government health expenditure per capita (current US$) [SH.XPD.GHED.PC.CD],...,Population density (people per sq. km of land area) [EN.POP.DNST],Land area (sq. km) [AG.LND.TOTL.K2],Urban land area (sq. km) [AG.LND.TOTL.UR.K2],Population in the largest city (% of urban population) [EN.URB.LCTY.UR.ZS],Population in largest city [EN.URB.LCTY],"Age dependency ratio, old (% of working-age population) [SP.POP.DPND.OL]",Age dependency ratio (% of working-age population) [SP.POP.DPND],Adjusted net national income per capita (current US$) [NY.ADJ.NNTY.PC.CD],Food imports (% of merchandise imports) [TM.VAL.FOOD.ZS.UN],Food production index (2004-2006 = 100) [AG.PRD.FOOD.XD]
0,2010.0,YR2010,Afghanistan,AFG,97.341930,8.569671,0.469157,2.255471,5.474624,2.495758,...,44.704082,652860.0,NaN,47.475708,3289005.0,4.703893,102.045823,477.307009,13.691848,115.98
1,2011.0,YR2011,Afghanistan,AFG,95.510252,8.561907,0.480000,2.188119,5.606225,2.890192,...,46.131503,652860.0,NaN,46.747239,3371653.0,4.714209,100.224461,517.448448,14.029271,110.74
2,2012.0,YR2012,Afghanistan,AFG,93.202852,7.897176,0.342887,1.370003,4.341895,2.267273,...,47.730564,652860.0,NaN,45.911611,3456496.0,4.723095,97.925947,554.779215,4.276023,122.13
3,2013.0,YR2013,Afghanistan,AFG,90.611139,8.805940,0.443358,1.775070,5.034762,2.817833,...,49.428038,652860.0,NaN,45.050246,3543232.0,4.727603,95.338742,550.956701,7.546840,119.31
4,2014.0,YR2014,Afghanistan,AFG,87.926203,9.528870,0.472657,1.860674,4.960258,2.981748,...,51.114778,652860.0,NaN,44.269634,3632269.0,4.722938,92.649141,529.876402,9.513261,123.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1948,2014.0,YR2014,Zimbabwe,ZWE,77.576935,7.869770,2.731566,13.357064,34.709609,34.554722,...,35.121316,386850.0,NaN,33.844820,1494660.0,5.263110,82.840045,1113.578145,15.139231,91.23
1949,2015.0,YR2015,Zimbabwe,ZWE,77.929769,7.452066,3.405413,16.593178,45.697564,43.088234,...,35.710557,386850.0,NaN,33.521843,1499723.0,5.208819,83.138588,1097.246724,16.742427,83.42
1950,2016.0,YR2016,Zimbabwe,ZWE,78.323173,7.652105,3.560712,15.234253,46.532455,45.871525,...,36.268295,386850.0,NaN,33.209409,1504803.0,5.253564,83.576737,1108.646033,20.126079,88.75
1951,2017.0,YR2017,Zimbabwe,ZWE,78.152707,6.635916,3.425181,15.234253,51.615793,56.854599,...,36.801719,386850.0,NaN,32.899038,1509901.0,5.313528,83.466235,1142.940418,14.888309,NaN
1952,2018.0,YR2018,Zimbabwe,ZWE,77.573229,NaN,NaN,NaN,NaN,NaN,...,37.324591,386850.0,NaN,32.576344,1515016.0,5.377887,82.951116,NaN,11.710690,NaN

In [33]:
for countri in range(0,1953,9):
    for yeari in range(1,9):
        for x in wdi:
            flag = pd.isnull(wdi.loc[(countri + yeari) ,x])
            if flag:
                wdi.loc[(countri + yeari) ,x] = wdi.loc[(countri + yeari-1) ,x]

In [34]:
for countri in range(0,1953,9):
    for yeari in range(1,9):
        for x in hns:
            flag = pd.isnull(hns.loc[(countri + yeari) ,x])
            if flag:
                hns.loc[(countri + yeari) ,x] = hns.loc[(countri + yeari-1) ,x]

In [35]:
hns.head(20)

,Year,Country Name,Country Code,Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS],Current health expenditure per capita (current US$) [SH.XPD.CHEX.PC.CD],"Current health expenditure per capita, PPP (current international $) [SH.XPD.CHEX.PP.CD]",Diabetes prevalence (% of population ages 20 to 79) [SH.STA.DIAB.ZS],"Life expectancy at birth, total (years) [SP.DYN.LE00.IN]","Labor force, total [SL.TLF.TOTL.IN]","Literacy rate, adult total (% of people ages 15 and above) [SE.ADT.LITR.ZS]",...,"People using at least basic drinking water services, urban (% of urban population) [SH.H2O.BASW.UR.ZS]",People using at least basic sanitation services (% of population) [SH.STA.BASS.ZS],"People using at least basic sanitation services, rural (% of rural population) [SH.STA.BASS.RU.ZS]","People using at least basic sanitation services, urban (% of urban population) [SH.STA.BASS.UR.ZS]",Rural population (% of total population) [SP.RUR.TOTL.ZS],"School enrollment, primary (% gross) [SE.PRM.ENRR]","School enrollment, secondary (% gross) [SE.SEC.ENRR]","School enrollment, tertiary (% gross) [SE.TER.ENRR]","Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age) [SH.ALC.PCAP.LI]",Urban population (% of total population) [SP.URB.TOTL.IN.ZS]
0,2010,Afghanistan,AFG,34.3,45.587750,132.271279,8.6,61.028,9572580.0,NaN,...,73.517656,34.177028,30.342450,46.496882,76.263,100.07170,50.56725,NaN,0.2,23.737
1,2011,Afghanistan,AFG,38.6,51.553259,138.822614,8.6,61.553,10008297.0,31.74112,...,76.600501,35.457100,31.299143,48.661582,76.052,97.64164,51.75691,3.62226,0.2,23.948
2,2012,Afghanistan,AFG,39.9,52.218506,143.965319,8.6,62.054,10534726.0,31.74112,...,79.721974,36.749962,32.256455,50.855408,75.840,103.49240,53.61805,3.62226,0.2,24.160
3,2013,Afghanistan,AFG,39.9,55.967550,164.160116,8.6,62.525,11128394.0,31.74112,...,82.882073,38.055832,33.214387,53.078361,75.627,104.49840,53.57513,3.62226,0.2,24.373
4,2014,Afghanistan,AFG,45.2,60.112761,176.930863,8.6,62.966,11752833.0,31.74112,...,86.080800,39.374932,34.172937,55.330440,75.413,105.91970,52.58290,8.23068,0.2,24.587
5,2015,Afghanistan,AFG,50.5,60.088813,183.927858,8.6,63.377,12381396.0,31.74112,...,89.318154,40.707707,35.132107,57.611646,75.197,105.77850,52.59281,8.23068,0.2,24.803
6,2016,Afghanistan,AFG,50.5,57.248760,162.781158,8.6,63.763,12931832.0,31.74112,...,92.594135,42.054183,36.091896,59.921979,74.980,105.77850,50.64540,8.23068,0.2,25.020
7,2017,Afghanistan,AFG,50.5,57.248760,162.781158,8.6,64.130,13467695.0,31.74112,...,95.908743,43.417610,37.052304,62.261438,74.750,102.31050,53.79764,8.23068,0.2,25.250
8,2018,Afghanistan,AFG,50.5,57.248760,162.781158,8.6,64.130,13952821.0,43.01972,...,95.908743,43.417610,37.052304,62.261438,74.505,102.31050,53.79764,9.68642,0.2,25.495
9,2010,Albania,ALB,NaN,203.208589,478.314737,4.5,76.562,1225928.0,NaN,...,92.873123,95.571700,92.949267,97.976648,47.837,93.49047,88.10389,44.54925,7.9,52.163
10,2011,Albania,ALB,NaN,246.803760,567.773829,4.5,76.914,1271089.0,96.84530,...,92.517469,96.184770,94.032867,98.074228,46.753,95.00608,89.79816,49.87870,7.9,53.247
11,2012,Albania,ALB,NaN,246.742546,611.466210,4.5,77.252,1322878.0,97.24697,...,92.290120,96.776433,95.116467,98.171807,45.670,97.58513,92.28983,59.25201,7.9,54.330
12,2013,Albania,ALB,NaN,277.668997,665.119156,4.5,77.554,1244852.0,97.24697,...,92.062771,97.312548,96.200067,98.208627,44.613,99.98391,96.25608,64.63443,7.9,55.387
13,2014,Albania,ALB,NaN,313.262897,770.335813,4.5,77.813,1268612.0,97.24697,...,91.835421,97.676855,96.885533,98.288014,43.577,104.10800,97.68487,65.78297,7.9,56.423
14,2015,Albania,ALB,NaN,264.434603,758.231531,4.5,78.025,1322597.0,97.24697,...,91.835421,97.691034,96.885533,98.288014,42.566,105.54300,97.38848,62.00762,7.9,57.434
15,2016,Albania,ALB,NaN,271.543043,759.666984,4.5,78.194,1321380.0,97.24697,...,91.835421,97.704877,96.885533,98.288014,41.579,105.55390,95.71500,58.38185,7.5,58.421
16,2017,Albania,ALB,NaN,271.543043,759.666984,4.5,78.333,1323346.0,97.24697,...,91.835421,97.718368,96.885533,98.288014,40.617,107.04660,95.26589,57.37526,7.5,59.383
17,2018,Albania,ALB,99.8,271.543043,759.666984,4.5,78.333,1322907.0,98.14115,...,91.835421,97.718368,96.885533,98.288014,39.681,106.99340,95.43233,54.96133,7.5,60.319
18,2010,Algeria,DZA,NaN,228.399544,645.287828,8.5,74.938,11082664.0,NaN,...,95.027100,86.560430,78.913464,90.235596,32.460,115.33760,96.93728,29.88943,0.7,67.540
19,2011,Algeria,DZA,NaN,286.151986,684.265345,8.5,75.199,11302087.0,NaN,...,95.110267,86.771741,79.572618,90.122951,31.764,116.56790,99.61435,31.21409,0.7,68.236

In [36]:
wdi.head(20)

,Time,Time Code,Country Name,Country Code,"Age dependency ratio, young (% of working-age population) [SP.POP.DPND.YG]",Current health expenditure (% of GDP) [SH.XPD.CHEX.GD.ZS],Domestic general government health expenditure (% of GDP) [SH.XPD.GHED.GD.ZS],Domestic general government health expenditure (% of general government expenditure) [SH.XPD.GHED.GE.ZS],Domestic general government health expenditure (% of current health expenditure) [SH.XPD.GHED.CH.ZS],Domestic general government health expenditure per capita (current US$) [SH.XPD.GHED.PC.CD],...,Population density (people per sq. km of land area) [EN.POP.DNST],Land area (sq. km) [AG.LND.TOTL.K2],Urban land area (sq. km) [AG.LND.TOTL.UR.K2],Population in the largest city (% of urban population) [EN.URB.LCTY.UR.ZS],Population in largest city [EN.URB.LCTY],"Age dependency ratio, old (% of working-age population) [SP.POP.DPND.OL]",Age dependency ratio (% of working-age population) [SP.POP.DPND],Adjusted net national income per capita (current US$) [NY.ADJ.NNTY.PC.CD],Food imports (% of merchandise imports) [TM.VAL.FOOD.ZS.UN],Food production index (2004-2006 = 100) [AG.PRD.FOOD.XD]
0,2010.0,YR2010,Afghanistan,AFG,97.341930,8.569671,0.469157,2.255471,5.474624,2.495758,...,44.704082,652860.0,NaN,47.475708,3289005.0,4.703893,102.045823,477.307009,13.691848,115.98
1,2011.0,YR2011,Afghanistan,AFG,95.510252,8.561907,0.480000,2.188119,5.606225,2.890192,...,46.131503,652860.0,NaN,46.747239,3371653.0,4.714209,100.224461,517.448448,14.029271,110.74
2,2012.0,YR2012,Afghanistan,AFG,93.202852,7.897176,0.342887,1.370003,4.341895,2.267273,...,47.730564,652860.0,NaN,45.911611,3456496.0,4.723095,97.925947,554.779215,4.276023,122.13
3,2013.0,YR2013,Afghanistan,AFG,90.611139,8.805940,0.443358,1.775070,5.034762,2.817833,...,49.428038,652860.0,NaN,45.050246,3543232.0,4.727603,95.338742,550.956701,7.546840,119.31
4,2014.0,YR2014,Afghanistan,AFG,87.926203,9.528870,0.472657,1.860674,4.960258,2.981748,...,51.114778,652860.0,NaN,44.269634,3632269.0,4.722938,92.649141,529.876402,9.513261,123.66
5,2015.0,YR2015,Afghanistan,AFG,85.245772,10.105348,0.522673,2.014406,5.172240,3.107937,...,52.712072,652860.0,NaN,43.623651,3723543.0,4.708320,89.954092,502.276410,19.227124,119.00
6,2016.0,YR2016,Afghanistan,AFG,83.205805,10.961983,0.556633,2.141105,5.077845,3.120401,...,54.197114,652860.0,NaN,43.118737,3817241.0,4.735985,87.941790,465.841583,23.559998,125.41
7,2017.0,YR2017,Afghanistan,AFG,81.249828,11.777194,0.600144,2.319116,5.095819,3.420449,...,55.595993,652860.0,NaN,42.699017,3913297.0,4.750925,86.000753,466.079081,23.559998,125.41
8,2018.0,YR2018,Afghanistan,AFG,79.319383,11.777194,0.600144,2.319116,5.095819,3.420449,...,56.937760,652860.0,NaN,42.331198,4011770.0,4.758273,84.077656,466.079081,32.271170,125.41
9,2010.0,YR2010,Albania,ALB,33.565374,NaN,4.470859,15.213978,NaN,181.341537,...,106.314635,27400.0,1689.403809,26.896472,408697.0,15.912535,49.477909,3530.690656,17.929999,118.43
10,2011.0,YR2011,Albania,ALB,31.802866,NaN,4.267042,14.752926,NaN,187.947144,...,106.029015,27400.0,1689.403809,26.924571,416504.0,16.315192,48.118058,3853.165353,16.608743,124.65
11,2012.0,YR2012,Albania,ALB,30.289696,NaN,4.059768,14.381474,NaN,171.283371,...,105.854051,27400.0,1689.403809,26.937063,424471.0,16.743384,47.033080,3644.843103,17.279086,133.04
12,2013.0,YR2013,Albania,ALB,29.041102,NaN,4.308756,14.783174,NaN,188.892960,...,105.660292,27400.0,1689.403809,26.977777,432590.0,17.215554,46.256656,3937.277061,17.704377,134.39
13,2014.0,YR2014,Albania,ALB,28.018308,NaN,4.432315,13.940282,NaN,200.323868,...,105.441752,27400.0,1689.403809,27.044958,440865.0,17.756372,45.774680,4038.014865,10.326218,141.72
14,2015.0,YR2015,Albania,ALB,27.172429,NaN,4.431013,14.554577,NaN,172.214035,...,105.135146,27400.0,1689.403809,27.156070,449298.0,18.377974,45.550402,3560.787907,14.497357,145.71
15,2016.0,YR2016,Albania,ALB,26.774948,NaN,4.383294,15.050119,NaN,177.758499,...,104.967190,27400.0,1689.403809,27.251470,457892.0,18.870086,45.645034,3776.111694,14.149751,150.93
16,2017.0,YR2017,Albania,ALB,26.264034,NaN,4.277554,14.678897,NaN,190.114563,...,104.870693,27400.0,1689.403809,27.347986,466651.0,19.418064,45.682097,4105.150515,14.113972,150.93
17,2018.0,YR2018,Albania,ALB,25.768823,NaN,4.277554,14.678897,NaN,190.114563,...,104.612263,27400.0,1689.403809,27.506393,475577.0,20.041214,45.810037,4105.150515,13.546110,150.93
18,2010.0,YR2010,Algeria,DZA,40.562547,5.117172,3.555521,9.544843,69.482148,158.696915,...,15.105534,2381740.0,30195.796880,10.008666,2432023.0,8.111989,48.674536,3407.251171,16.300203,130.29
19,2011.0,YR2011,Algeria,DZA,40.993535,5.267481,3.720153,9.271831,70.624894,202.094528,...,15.392715,2381740.0,30195.796880,9.846663,2463271.0,8.219559,49.213095,3963.324724,22.791169,144.10

Now as our 2018 Values have the newest data available in them we do not need Year's datas other than 2018.

In [37]:
wdi = wdi[wdi["Time"] == 2018]
hns = hns[hns["Year"] == "2018"]

In [38]:
wdi.reset_index(drop=True,inplace=True)
wdi

,Time,Time Code,Country Name,Country Code,"Age dependency ratio, young (% of working-age population) [SP.POP.DPND.YG]",Current health expenditure (% of GDP) [SH.XPD.CHEX.GD.ZS],Domestic general government health expenditure (% of GDP) [SH.XPD.GHED.GD.ZS],Domestic general government health expenditure (% of general government expenditure) [SH.XPD.GHED.GE.ZS],Domestic general government health expenditure (% of current health expenditure) [SH.XPD.GHED.CH.ZS],Domestic general government health expenditure per capita (current US$) [SH.XPD.GHED.PC.CD],...,Population density (people per sq. km of land area) [EN.POP.DNST],Land area (sq. km) [AG.LND.TOTL.K2],Urban land area (sq. km) [AG.LND.TOTL.UR.K2],Population in the largest city (% of urban population) [EN.URB.LCTY.UR.ZS],Population in largest city [EN.URB.LCTY],"Age dependency ratio, old (% of working-age population) [SP.POP.DPND.OL]",Age dependency ratio (% of working-age population) [SP.POP.DPND],Adjusted net national income per capita (current US$) [NY.ADJ.NNTY.PC.CD],Food imports (% of merchandise imports) [TM.VAL.FOOD.ZS.UN],Food production index (2004-2006 = 100) [AG.PRD.FOOD.XD]
0,2018.0,YR2018,Afghanistan,AFG,79.319383,11.777194,0.600144,2.319116,5.095819,3.420449,...,56.937760,652860.0,NaN,42.331198,4011770.0,4.758273,84.077656,466.079081,32.271170,125.41
1,2018.0,YR2018,Albania,ALB,25.768823,NaN,4.277554,14.678897,NaN,190.114563,...,104.612263,27400.0,1689.403809,27.506393,475577.0,20.041214,45.810037,4105.150515,13.546110,150.93
2,2018.0,YR2018,Algeria,DZA,47.486590,6.374322,4.204164,10.734123,65.954691,170.489120,...,17.730075,2381740.0,30195.796880,8.782310,2693542.0,10.021442,57.508032,3257.676874,20.241169,151.62
3,2018.0,YR2018,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,...,277.325000,200.0,116.166870,NaN,NaN,NaN,NaN,NaN,NaN,120.97
4,2018.0,YR2018,Andorra,AND,NaN,10.320552,5.060373,14.017555,49.031994,1981.278320,...,163.842553,470.0,NaN,NaN,NaN,NaN,NaN,NaN,22.200559,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,2018.0,YR2018,Virgin Islands (U.S.),VIR,32.318325,NaN,NaN,NaN,NaN,NaN,...,305.648571,350.0,302.013214,NaN,NaN,31.621050,63.939375,NaN,NaN,107.17
213,2018.0,YR2018,West Bank and Gaza,PSE,67.244146,NaN,NaN,NaN,NaN,NaN,...,758.984551,6020.0,2496.458252,19.357419,673638.0,5.409757,72.653903,NaN,28.317591,87.65
214,2018.0,YR2018,"Yemen, Rep.",YEM,68.884875,4.234575,0.431183,2.228724,10.182443,7.335378,...,53.977853,527970.0,4703.399902,26.615465,2779317.0,5.001439,73.886314,1060.494887,46.925913,141.69
215,2018.0,YR2018,Zambia,ZMB,84.842512,4.470341,1.727027,6.856654,38.633010,26.134714,...,23.341479,743390.0,NaN,33.420934,2523844.0,3.964332,88.806844,1129.393375,5.276711,179.77
216,2018.0,YR2018,Zimbabwe,ZWE,77.573229,6.635916,3.425181,15.234253,51.615793,56.854599,...,37.324591,386850.0,NaN,32.576344,1515016.0,5.377887,82.951116,1142.940418,11.710690,88.75

In [39]:
hns.reset_index(drop=True,inplace=True)
hns

,Year,Country Name,Country Code,Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS],Current health expenditure per capita (current US$) [SH.XPD.CHEX.PC.CD],"Current health expenditure per capita, PPP (current international $) [SH.XPD.CHEX.PP.CD]",Diabetes prevalence (% of population ages 20 to 79) [SH.STA.DIAB.ZS],"Life expectancy at birth, total (years) [SP.DYN.LE00.IN]","Labor force, total [SL.TLF.TOTL.IN]","Literacy rate, adult total (% of people ages 15 and above) [SE.ADT.LITR.ZS]",...,"People using at least basic drinking water services, urban (% of urban population) [SH.H2O.BASW.UR.ZS]",People using at least basic sanitation services (% of population) [SH.STA.BASS.ZS],"People using at least basic sanitation services, rural (% of rural population) [SH.STA.BASS.RU.ZS]","People using at least basic sanitation services, urban (% of urban population) [SH.STA.BASS.UR.ZS]",Rural population (% of total population) [SP.RUR.TOTL.ZS],"School enrollment, primary (% gross) [SE.PRM.ENRR]","School enrollment, secondary (% gross) [SE.SEC.ENRR]","School enrollment, tertiary (% gross) [SE.TER.ENRR]","Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age) [SH.ALC.PCAP.LI]",Urban population (% of total population) [SP.URB.TOTL.IN.ZS]
0,2018,Afghanistan,AFG,50.5,57.248760,162.781158,8.6,64.130000,13952821.0,43.01972,...,95.908743,43.417610,37.052304,62.261438,74.505,102.31050,53.79764,9.68642,0.2,25.495
1,2018,Albania,ALB,99.8,271.543043,759.666984,4.5,78.333000,1322907.0,98.14115,...,91.835421,97.718368,96.885533,98.288014,39.681,106.99340,95.43233,54.96133,7.5,60.319
2,2018,Algeria,DZA,96.6,260.412579,998.153754,8.5,76.499000,12187913.0,81.40784,...,95.442932,87.586571,82.209238,89.672369,27.371,109.88280,99.61435,51.36567,0.9,72.629
3,2018,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,54.454760,NaN,NaN,12.847,NaN,NaN,NaN,NaN,87.153
4,2018,Andorra,AND,NaN,3834.730581,4978.706602,6.6,NaN,NaN,NaN,...,100.000000,99.999996,100.000000,100.000000,11.938,NaN,NaN,NaN,11.3,88.062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,2018,Virgin Islands (U.S.),VIR,NaN,NaN,NaN,9.9,79.419512,51011.0,NaN,...,NaN,99.371278,NaN,NaN,4.279,NaN,NaN,NaN,NaN,95.721
213,2018,West Bank and Gaza,PSE,99.6,NaN,NaN,8.6,73.740000,1267515.0,97.21861,...,97.108901,96.939007,96.138193,97.193367,23.836,98.60411,89.48775,44.25381,NaN,76.164
214,2018,"Yemen, Rep.",YEM,44.7,72.039469,144.518254,3.0,66.086000,6625451.0,NaN,...,79.052100,59.053003,42.838786,87.858275,63.358,93.63748,51.58068,10.15192,0.1,36.642
215,2018,Zambia,ZMB,63.3,56.544182,175.178352,4.0,63.043000,7183708.0,86.74796,...,83.863119,26.370118,18.932012,36.239594,56.479,98.71552,NaN,4.11603,4.8,43.521
216,2018,Zimbabwe,ZWE,78.1,93.942225,185.048282,4.1,60.812000,6948204.0,88.69342,...,93.997669,36.221398,31.466653,46.215993,67.791,109.89280,52.40567,10.00655,4.8,32.209

Now I will save them in order to merge them into one with my main data.

In [41]:
hns.to_csv("hns.csv")
wdi.to_csv("wdi.csv")